apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: njayasee-carla-cache # Change this to your njayasee
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
